packages:
  - '.'

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@parcel/watcher'
  - electron
  - esbuild

# required to support Electron's packaging toolchain when using pnpm
nodeLinker: 'hoisted'
